# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyjzlScZCXOx4KqwKbugqocZjcEQqtwo
"""

import random
import time

# -----------------------------
# Data Structures
# -----------------------------
class Dataset:
    def __init__(self):
        self.id = None
        self.values = []
        self.original = []
        self.size = 0
        self.isSorted = False


class SearchResult:
    def __init__(self, index, comparisons, found):
        self.index = index
        self.comparisons = comparisons
        self.found = found


class SortResult:
    def __init__(self, comparisons, dataMoves):
        self.comparisons = comparisons
        self.dataMoves = dataMoves


# -----------------------------
# Helper Functions
# -----------------------------
def generate_unique_id(existing_ids):
    while True:
        new_id = 10000 + random.randint(0, 89999)
        if new_id not in existing_ids:
            return new_id


def check_sorted(arr):
    return all(arr[i] <= arr[i + 1] for i in range(len(arr) - 1))


def display_array(arr):
    print("Values:", *arr)


# -----------------------------
# Search Algorithms
# -----------------------------
def linear_search(arr, target):
    comparisons = 0
    for i in range(len(arr)):
        comparisons += 1
        if arr[i] == target:
            return SearchResult(i, comparisons, True)
    return SearchResult(-1, comparisons, False)


def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    comparisons = 0

    while left <= right:
        mid = (left + right) // 2
        comparisons += 1

        if arr[mid] == target:
            return SearchResult(mid, comparisons, True)
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return SearchResult(-1, comparisons, False)


# -----------------------------
# Sorting Algorithms
# -----------------------------
def selection_sort(arr):
    comparisons = 0
    swaps = 0
    n = len(arr)

    for i in range(n):
        min_idx = i
        for j in range(i + 1, n):
            comparisons += 1
            if arr[j] < arr[min_idx]:
                min_idx = j

        if min_idx != i:
            arr[i], arr[min_idx] = arr[min_idx], arr[i]
            swaps += 1

    return SortResult(comparisons, swaps)


def insertion_sort(arr):
    comparisons = 0
    moves = 0

    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1

        while j >= 0:
            comparisons += 1
            if arr[j] > key:
                arr[j + 1] = arr[j]
                moves += 1
                j -= 1
            else:
                break

        arr[j + 1] = key
        moves += 1

    return SortResult(comparisons, moves)


# -----------------------------
# Main Program
# -----------------------------
def main():
    dataset = Dataset()
    used_ids = set()

    while True:
        print("\n*************** Algorithm Workbench ***************")
        print("1. Create a new dataset")
        print("2. Display the current dataset")
        print("3. Perform Linear Search")
        print("4. Perform Binary Search")
        print("5. Sort using Selection Sort")
        print("6. Sort using Insertion Sort")
        print("7. Restore original dataset")
        print("0. Exit")

        choice = input("Choice: ")

        # 1. Create Dataset
        if choice == "1":
            size = int(input("Enter dataset size (1-100): "))

            print("1. Manual\n2. Random")
            method = input("Choice: ")

            values = []

            if method == "1":
                for i in range(size):
                    values.append(int(input(f"Enter value {i+1}: ")))
            else:
                min_val = int(input("Min value: "))
                max_val = int(input("Max value: "))
                values = [random.randint(min_val, max_val) for _ in range(size)]

            dataset.id = generate_unique_id(used_ids)
            used_ids.add(dataset.id)

            dataset.values = values[:]
            dataset.original = values[:]
            dataset.size = size
            dataset.isSorted = check_sorted(values)

            print("\nDataset created!")
            print("ID:", dataset.id)
            print("Size:", dataset.size)
            print("Sorted:", "Yes" if dataset.isSorted else "No")
            display_array(dataset.values)


        # 2. Display
        elif choice == "2":
            if dataset.size == 0:
                print("No dataset exists.")
            else:
                print("ID:", dataset.id)
                print("Size:", dataset.size)
                print("Sorted:", "Yes" if dataset.isSorted else "No")
                display_array(dataset.values)

        # 3. Linear Search
        elif choice == "3":
            if dataset.size == 0:
                print("No dataset exists.")
                continue

            target = int(input("Enter target: "))
            result = linear_search(dataset.values, target)

            print("\n--- Linear Search ---")
            print("Target:", target)
            print("Found:", "Yes" if result.found else "No")
            print("Index:", result.index)
            print("Comparisons:", result.comparisons)

            print("\nComplexity:")
            print("Best: O(1)")
            print("Average: O(n)")
            print("Worst: O(n)")

        # 4. Binary Search
        elif choice == "4":
            if dataset.size == 0:
                print("No dataset exists.")
                continue

            if not dataset.isSorted:
                print("Binary Search cannot run (not sorted).")
                continue

            target = int(input("Enter target: "))
            result = binary_search(dataset.values, target)

            print("\n--- Binary Search ---")
            print("Target:", target)
            print("Found:", "Yes" if result.found else "No")
            print("Index:", result.index)
            print("Comparisons:", result.comparisons)

            print("\nComplexity:")
            print("Best: O(1)")
            print("Average: O(log n)")
            print("Worst: O(log n)")

        # 5. Selection Sort
        elif choice == "5":
          if dataset.size == 0:
            print("No dataset exists.")
            pause()
            continue

          print("Choice: 5")
          print("\nBefore Selection Sort:")
          display_array(dataset.values)

          result = selection_sort(dataset.values)
          dataset.isSorted = True

          print("\nAfter Selection Sort:")
          display_array(dataset.values)

          print("Comparisons:", result.comparisons)
          print("Swaps:", result.dataMoves)

          print("\nTheoretical Complexity:")
          print("Time Complexity: O(n^2)")
          print("Auxiliary Space: O(1)")


        # 6. Insertion Sort
        elif choice == "6":
            if dataset.size == 0:
                print("No dataset exists.")
                continue

            print("Before:")
            display_array(dataset.values)

            result = insertion_sort(dataset.values)
            dataset.isSorted = True

            print("After:")
            display_array(dataset.values)
            print("Comparisons:", result.comparisons)
            print("Moves:", result.dataMoves)

        # 7. Restore
        elif choice == "7":
            if dataset.size == 0:
                print("No dataset exists.")
                continue

            dataset.values = dataset.original[:]
            dataset.isSorted = check_sorted(dataset.values)

            print("Dataset restored!")
            display_array(dataset.values)

        # 0. Exit
        elif choice == "0":
            print("Goodbye!")
            break

        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main()